#!/bin/bash

echo 'So Roda com SUDO'
sudo su - root
echo 'verificando se estou como SUDO'
if [ "$(whoami)" != "root" ]; then
    echo "Você não está executando como root (sudo). Execute com sudo."
    exit 1
fi

echo 'Iniciando....'

apt update -y

echo 'Install JDK JAVA'
apt install openjdk-17-jdk -y



echo 'First, add the repository key to the system'
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -

sleep 1

echo 'Next, let’s append the Debian package repository address to the server’s sources.list'
sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

echo 'update'
sudo apt update

echo 'Install JenKins'
sudo apt install jenkins

sudo systemctl enable jenkins

sudo systemctl start jenkins

echo 'STATUS SERVICE'

sudo systemctl status jenkins

echo 'Pegando Password defalut'
sleep 5

sudo cat /var/lib/jenkins/secrets/initialAdminPassword

