#!/bin/bash


# Diretório que contém a chave PEM
PEM_DIR="./pem"

# Comandos que você deseja executar em cada servidor
COMMANDS=(
      "curl -s https://raw.githubusercontent.com/JonathanFreitas/AutoLinux/main/remove_images_docker.sh | bash ;"
      "sleep 2;"
      "echo 'Feito! crontab';"
      "crontab -l;"
      
      

)

# Loop para acessar cada servidor e executar os comandos
while IFS= read -r IP; do
  echo "Acessando o servidor $IP"
  ping -c 2 $IP
  for CMD in "${COMMANDS[@]}"; do
    ssh -i "${PEM_DIR}" -p22 root@$IP "$CMD"
  done

  echo "Comandos executados no servidor $IP"
done < "lista_ips.txt"
